### ISSUE TITLE
NLST dataset

### ISSUE THREAD

**Issue by sjjadsa** [liupei101/AdvMIL#3]
Your paper mentions that NLST is a publicly available dataset, where can I find the download address?

**Comment by liupei101** [comment]
Hello, sjjadsa. 

Data and images from the NLST study are available upon request. You can submit your request at [NLST official website](https://cdas.cancer.gov/learn/nlst/instructions/). It is not hard to get the request approved. Once approved, you will receive an official link for downloading the images.

Best regards.

**Comment by sjjadsa** [comment]
got it ，thanks
