### ISSUE TITLE
TCGA-LUAD中的数据没有足够的dimension levels

### ISSUE THREAD

**Issue by XiaoXueShengwangrui** [liupei101/AdvMIL#4]
您好，
在您repo中使用CLAM提取image patch的过程中，当patch-level=2时，会存在部分的SVS文件没有足够的dimension levels。**(在我之前使用CLAM做MIL分类时，并未使用到patch-level=2的情况，我仅使用patch-level=0，1)**
```
# DATA_DIRECTORY should be the path to raw images (e.g., svs files). 
# '/data/nlst/processed/tiles-l2-s256' is the path for saving patching results.
python create_patches_fp.py \
    --source DATA_DIRECTORY \
    --save_dir /data/nlst/processed/tiles-l2-s256 \
    --patch_level 2 --patch_size 256 --seg --patch --stitch
```

例如： _TCGA-05-4384-01Z-00-DX1.CA68BF29-BBE3-4C8E-B48B-554431A9EE13.svs_  
这张slide的levels_dimension为 level0=(10000,9419), level1=1(2500,2354),  level2=()。

<img width="934" alt="image" src="https://github.com/user-attachments/assets/79430f51-e0f2-43db-b834-6c6d679c241f">

在遇到没有足够的level dimension时，您是如何处理的？因为您文中没有采用LUAD的数据集，是否其他数据集中不存在这种问题？

期待您的回复！
@liupei101

**Comment by liupei101** [comment]
您好，@XiaoXueShengwangrui

论文中使用的3个数据集没有遇到您提到的情况。

当数据中遇到没有足够的level dimension时，您可以采用常用的图像缩放算法（如`Image.resize`）对`level=1`图像进行适当的downsample，来得到您预期`level=2`的图像。这种方法可以作为一个参考、可选方案来近似地获得`level=2`下的图像，实际病理切片中`level=2`是通过调整显微镜到适当倍率后，重新成像得到。希望对您有用。

祝顺利

**Comment by XiaoXueShengwangrui** [comment]
> 您好，@XiaoXueShengwangrui
> 
> 论文中使用的3个数据集没有遇到您提到的情况。
> 
> 当数据中遇到没有足够的level dimension时，您可以采用常用的图像缩放算法（如`Image.resize`）对`level=1`图像进行适当的downsample，来得到您预期`level=2`的图像。这种方法可以作为一个参考、可选方案来近似地获得`level=2`下的图像，实际病理切片中`level=2`是通过调整显微镜到适当倍率后，重新成像得到。希望对您有用。
> 
> 祝顺利

谢谢您的解答！
