### ISSUE TITLE
data_spilt的划分

### ISSUE THREAD

**Issue by sjjadsa** [liupei101/AdvMIL#5]
作者您好。注意到data_spilt文件夹里有很多npz文件，这是五折交叉验证的训练集、验证集和测试集。请问有没有开箱即用的代码快速得到这些npz文件？

**Comment by liupei101** [comment]
您好。您可以参考[这个Notebook](https://github.com/liupei101/PseMix/blob/main/notebooks/generate_data_split_npz.ipynb)，然后做适当修改以得到适用您自己数据集的npz文件。
